version: "2"

services:

  web:
    build: ./web
    links:
      - db
    ports:
      - "80:80"
    volumes:
      - ./html/:/var/www/html
    working_dir: /var/www/html
    command: app/bin/cake server -H webhost -p 80
    extra_hosts:
      - "webhost:192.168.99.100"
    hostname: webhost

  db:
    build: ./db
    ports:
      - "30000:3306"
    volumes:
      - ./db/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password