-- MySQL Script generated by MySQL Workbench
-- Wed Dec 13 00:30:28 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Users` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Publishers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Publishers` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Publishers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Books`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Books` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Books` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `auther` VARCHAR(45) NULL,
  `price` INT NULL,
  `Publishers_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `Publishers_id_idx` (`Publishers_id` ASC),
  CONSTRAINT `Publishers_id`
    FOREIGN KEY (`Publishers_id`)
    REFERENCES `mydb`.`Publishers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Opinions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Opinions` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Opinions` (
  `Books_id` INT NULL,
  `Users_id` INT NULL,
  `impression` VARCHAR(200) NULL,
  INDEX `Users_id_idx` (`Users_id` ASC),
  INDEX `Boods_id_idx` (`Books_id` ASC),
  CONSTRAINT `Users_id`
    FOREIGN KEY (`Users_id`)
    REFERENCES `mydb`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Boods_id`
    FOREIGN KEY (`Books_id`)
    REFERENCES `mydb`.`Books` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Recommendations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Recommendations` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Recommendations` (
  `Books_id` INT NULL,
  `Users_id` INT NULL,
  `name` VARCHAR(45) NULL,
  INDEX `Books_id_idx` (`Books_id` ASC),
  INDEX `Users_id_idx` (`Users_id` ASC),
  CONSTRAINT `Books_r_id`
    FOREIGN KEY (`Books_id`)
    REFERENCES `mydb`.`Books` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Users_r_id`
    FOREIGN KEY (`Users_id`)
    REFERENCES `mydb`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
KEY_BLOCK_SIZE = 4;

SET SQL_MODE = '';
GRANT USAGE ON *.* TO root;
 DROP USER root;
SET SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';
CREATE USER 'root' IDENTIFIED BY 'password';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
